codecov:
  require_ci_to_pass: yes
coverage:
  status:
    project:
      default: false
        target: 80%
        threshold: 5%
        informational: true
    patch:
      default:
        target: 80%
        threshold: 5%
        informational: true